name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Angular app
        working-directory: ./angular-app
        run: |
          npm install
          npm run build --prod


      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Spring Boot app
        working-directory: ./springboot
        run: ./mvnw clean package -DskipTests


      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: |
          docker compose build
          docker compose up -d
